
\ words to enable RTC_GPIO

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE1_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE1_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO0.ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE2_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE2_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO1.ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE3_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE3_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO2.ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE4_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE4_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO3.ENABLE

RTCIO_ADC_PAD_REG RTCIO_ADC_ADC1_MUX_SEL_S 1 1
RTCIO_ADC_PAD_REG RTCIO_ADC_ADC1_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO4.ENABLE

RTCIO_ADC_PAD_REG RTCIO_ADC_ADC2_MUX_SEL_S 1 1
RTCIO_ADC_PAD_REG RTCIO_ADC_ADC2_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO5.ENABLE

RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_MUX_SEL_S 1 1
RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO6.ENABLE

RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_MUX_SEL_S 1 1
RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO7.ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_MUX_SEL_S 1 1
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO8.ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_MUX_SEL_S 1 1
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO9.ENABLE

RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO10.ENABLE

RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO11.ENABLE

RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO12.ENABLE

RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO13.ENABLE

RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO14.ENABLE

RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO15.ENABLE

RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO16.ENABLE

RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO17.ENABLE

\ words to enable output on RTC_GPIO

\ RTCIO_RTC_GPIO_ENABLE_W1TS_REG RTCIO_RTC_GPIO_ENABLE_W1TS_S 12 + 1 1
\ WRITE_RTC_REG RTC_GPIO12.OUTPUT_ENABLE

: --CREATE-OUTPUTENABLE ( n -- )
    RTCIO_RTC_GPIO_ENABLE_W1TS_REG
    SWAP RTCIO_RTC_GPIO_ENABLE_W1TS_S +
    1 1
    WRITE_RTC_REG
;

0  --CREATE-OUTPUTENABLE RTC_GPIO0.OUTPUT_ENABLE
1  --CREATE-OUTPUTENABLE RTC_GPIO1.OUTPUT_ENABLE
2  --CREATE-OUTPUTENABLE RTC_GPIO2.OUTPUT_ENABLE
3  --CREATE-OUTPUTENABLE RTC_GPIO3.OUTPUT_ENABLE
4  --CREATE-OUTPUTENABLE RTC_GPIO4.OUTPUT_ENABLE
5  --CREATE-OUTPUTENABLE RTC_GPIO5.OUTPUT_ENABLE
6  --CREATE-OUTPUTENABLE RTC_GPIO6.OUTPUT_ENABLE
7  --CREATE-OUTPUTENABLE RTC_GPIO7.OUTPUT_ENABLE
8  --CREATE-OUTPUTENABLE RTC_GPIO8.OUTPUT_ENABLE
9  --CREATE-OUTPUTENABLE RTC_GPIO9.OUTPUT_ENABLE
10 --CREATE-OUTPUTENABLE RTC_GPIO10.OUTPUT_ENABLE
11 --CREATE-OUTPUTENABLE RTC_GPIO11.OUTPUT_ENABLE
12 --CREATE-OUTPUTENABLE RTC_GPIO12.OUTPUT_ENABLE
13 --CREATE-OUTPUTENABLE RTC_GPIO13.OUTPUT_ENABLE
14 --CREATE-OUTPUTENABLE RTC_GPIO14.OUTPUT_ENABLE
15 --CREATE-OUTPUTENABLE RTC_GPIO15.OUTPUT_ENABLE
16 --CREATE-OUTPUTENABLE RTC_GPIO16.OUTPUT_ENABLE
17 --CREATE-OUTPUTENABLE RTC_GPIO17.OUTPUT_ENABLE

\ words to set RTC_GPIO high

\ RTCIO_RTC_GPIO_OUT_W1TS_REG RTCIO_RTC_GPIO_OUT_DATA_W1TS_S 12 + 1 1
\ WRITE_RTC_REG RTC_GPIO12.SET_HIGH

: --CREATE-SETHIGH ( n -- )
    RTCIO_RTC_GPIO_OUT_W1TS_REG
    SWAP RTCIO_RTC_GPIO_OUT_DATA_W1TS_S +
    1 1
    WRITE_RTC_REG
;
0  --CREATE-SETHIGH RTC_GPIO0.SET_HIGH
1  --CREATE-SETHIGH RTC_GPIO1.SET_HIGH
2  --CREATE-SETHIGH RTC_GPIO2.SET_HIGH
3  --CREATE-SETHIGH RTC_GPIO3.SET_HIGH
4  --CREATE-SETHIGH RTC_GPIO4.SET_HIGH
5  --CREATE-SETHIGH RTC_GPIO5.SET_HIGH
6  --CREATE-SETHIGH RTC_GPIO6.SET_HIGH
7  --CREATE-SETHIGH RTC_GPIO7.SET_HIGH
8  --CREATE-SETHIGH RTC_GPIO8.SET_HIGH
9  --CREATE-SETHIGH RTC_GPIO9.SET_HIGH
10 --CREATE-SETHIGH RTC_GPIO10.SET_HIGH
11 --CREATE-SETHIGH RTC_GPIO11.SET_HIGH
12 --CREATE-SETHIGH RTC_GPIO12.SET_HIGH
13 --CREATE-SETHIGH RTC_GPIO13.SET_HIGH
14 --CREATE-SETHIGH RTC_GPIO14.SET_HIGH
15 --CREATE-SETHIGH RTC_GPIO15.SET_HIGH
16 --CREATE-SETHIGH RTC_GPIO16.SET_HIGH
17 --CREATE-SETHIGH RTC_GPIO17.SET_HIGH

\ words to set RTC_GPIO low

\ RTCIO_RTC_GPIO_OUT_W1TC_REG RTCIO_RTC_GPIO_OUT_DATA_W1TC_S 12 + 1 1
\ WRITE_RTC_REG RTC_GPIO12.SET_LOW

: --CREATE-SETLOW ( n -- )
    RTCIO_RTC_GPIO_OUT_W1TC_REG
    SWAP RTCIO_RTC_GPIO_OUT_DATA_W1TC_S +
    1 1
    WRITE_RTC_REG
;
0  --CREATE-SETLOW RTC_GPIO0.SET_LOW
1  --CREATE-SETLOW RTC_GPIO1.SET_LOW
2  --CREATE-SETLOW RTC_GPIO2.SET_LOW
3  --CREATE-SETLOW RTC_GPIO3.SET_LOW
4  --CREATE-SETLOW RTC_GPIO4.SET_LOW
5  --CREATE-SETLOW RTC_GPIO5.SET_LOW
6  --CREATE-SETLOW RTC_GPIO6.SET_LOW
7  --CREATE-SETLOW RTC_GPIO7.SET_LOW
8  --CREATE-SETLOW RTC_GPIO8.SET_LOW
9  --CREATE-SETLOW RTC_GPIO9.SET_LOW
10 --CREATE-SETLOW RTC_GPIO10.SET_LOW
11 --CREATE-SETLOW RTC_GPIO11.SET_LOW
12 --CREATE-SETLOW RTC_GPIO12.SET_LOW
13 --CREATE-SETLOW RTC_GPIO13.SET_LOW
14 --CREATE-SETLOW RTC_GPIO14.SET_LOW
15 --CREATE-SETLOW RTC_GPIO15.SET_LOW
16 --CREATE-SETLOW RTC_GPIO16.SET_LOW
17 --CREATE-SETLOW RTC_GPIO17.SET_LOW

\ helper words to set RTC_GPIO levels

: RTC_GPIO0.SET  ( n -- ) IF RTC_GPIO0.SET_HIGH  ELSE RTC_GPIO0.SET_LOW  THEN ;
: RTC_GPIO1.SET  ( n -- ) IF RTC_GPIO1.SET_HIGH  ELSE RTC_GPIO1.SET_LOW  THEN ;
: RTC_GPIO2.SET  ( n -- ) IF RTC_GPIO2.SET_HIGH  ELSE RTC_GPIO2.SET_LOW  THEN ;
: RTC_GPIO3.SET  ( n -- ) IF RTC_GPIO3.SET_HIGH  ELSE RTC_GPIO3.SET_LOW  THEN ;
: RTC_GPIO4.SET  ( n -- ) IF RTC_GPIO4.SET_HIGH  ELSE RTC_GPIO4.SET_LOW  THEN ;
: RTC_GPIO5.SET  ( n -- ) IF RTC_GPIO5.SET_HIGH  ELSE RTC_GPIO5.SET_LOW  THEN ;
: RTC_GPIO6.SET  ( n -- ) IF RTC_GPIO6.SET_HIGH  ELSE RTC_GPIO6.SET_LOW  THEN ;
: RTC_GPIO7.SET  ( n -- ) IF RTC_GPIO7.SET_HIGH  ELSE RTC_GPIO7.SET_LOW  THEN ;
: RTC_GPIO8.SET  ( n -- ) IF RTC_GPIO8.SET_HIGH  ELSE RTC_GPIO8.SET_LOW  THEN ;
: RTC_GPIO9.SET  ( n -- ) IF RTC_GPIO9.SET_HIGH  ELSE RTC_GPIO9.SET_LOW  THEN ;
: RTC_GPIO10.SET ( n -- ) IF RTC_GPIO10.SET_HIGH ELSE RTC_GPIO10.SET_LOW THEN ;
: RTC_GPIO11.SET ( n -- ) IF RTC_GPIO11.SET_HIGH ELSE RTC_GPIO11.SET_LOW THEN ;
: RTC_GPIO12.SET ( n -- ) IF RTC_GPIO12.SET_HIGH ELSE RTC_GPIO12.SET_LOW THEN ;
: RTC_GPIO13.SET ( n -- ) IF RTC_GPIO13.SET_HIGH ELSE RTC_GPIO13.SET_LOW THEN ;
: RTC_GPIO14.SET ( n -- ) IF RTC_GPIO14.SET_HIGH ELSE RTC_GPIO14.SET_LOW THEN ;
: RTC_GPIO15.SET ( n -- ) IF RTC_GPIO15.SET_HIGH ELSE RTC_GPIO15.SET_LOW THEN ;
: RTC_GPIO16.SET ( n -- ) IF RTC_GPIO16.SET_HIGH ELSE RTC_GPIO16.SET_LOW THEN ;
: RTC_GPIO17.SET ( n -- ) IF RTC_GPIO17.SET_HIGH ELSE RTC_GPIO17.SET_LOW THEN ;

\ GPIO equivalents

: GPIO36.ENABLE ( -- ) RTC_GPIO0.ENABLE ;
: GPIO36.OUTPUT_ENABLE ( -- ) RTC_GPIO0.OUTPUT_ENABLE ;
: GPIO36.SET_HIGH ( -- ) RTC_GPIO0.SET_HIGH ;
: GPIO36.SET_LOW ( -- ) RTC_GPIO0.SET_LOW ;
: GPIO36.SET ( n -- ) RTC_GPIO0.SET ;

: GPIO37.ENABLE ( -- ) RTC_GPIO1.ENABLE ;
: GPIO37.OUTPUT_ENABLE ( -- ) RTC_GPIO1.OUTPUT_ENABLE ;
: GPIO37.SET_HIGH ( -- ) RTC_GPIO1.SET_HIGH ;
: GPIO37.SET_LOW ( -- ) RTC_GPIO1.SET_LOW ;
: GPIO37.SET ( n -- ) RTC_GPIO1.SET ;

: GPIO38.ENABLE ( -- ) RTC_GPIO2.ENABLE ;
: GPIO38.OUTPUT_ENABLE ( -- ) RTC_GPIO2.OUTPUT_ENABLE ;
: GPIO38.SET_HIGH ( -- ) RTC_GPIO2.SET_HIGH ;
: GPIO38.SET_LOW ( -- ) RTC_GPIO2.SET_LOW ;
: GPIO38.SET ( n -- ) RTC_GPIO2.SET ;

: GPIO39.ENABLE ( -- ) RTC_GPIO3.ENABLE ;
: GPIO39.OUTPUT_ENABLE ( -- ) RTC_GPIO3.OUTPUT_ENABLE ;
: GPIO39.SET_HIGH ( -- ) RTC_GPIO3.SET_HIGH ;
: GPIO39.SET_LOW ( -- ) RTC_GPIO3.SET_LOW ;
: GPIO39.SET ( n -- ) RTC_GPIO3.SET ;

: GPIO34.ENABLE ( -- ) RTC_GPIO4.ENABLE ;
: GPIO34.OUTPUT_ENABLE ( -- ) RTC_GPIO4.OUTPUT_ENABLE ;
: GPIO34.SET_HIGH ( -- ) RTC_GPIO4.SET_HIGH ;
: GPIO34.SET_LOW ( -- ) RTC_GPIO4.SET_LOW ;
: GPIO34.SET ( n -- ) RTC_GPIO4.SET ;

: GPIO35.ENABLE ( -- ) RTC_GPIO5.ENABLE ;
: GPIO35.OUTPUT_ENABLE ( -- ) RTC_GPIO5.OUTPUT_ENABLE ;
: GPIO35.SET_HIGH ( -- ) RTC_GPIO5.SET_HIGH ;
: GPIO35.SET_LOW ( -- ) RTC_GPIO5.SET_LOW ;
: GPIO35.SET ( n -- ) RTC_GPIO5.SET ;

: GPIO25.ENABLE ( -- ) RTC_GPIO6.ENABLE ;
: GPIO25.OUTPUT_ENABLE ( -- ) RTC_GPIO6.OUTPUT_ENABLE ;
: GPIO25.SET_HIGH ( -- ) RTC_GPIO6.SET_HIGH ;
: GPIO25.SET_LOW ( -- ) RTC_GPIO6.SET_LOW ;
: GPIO25.SET ( n -- ) RTC_GPIO6.SET ;

: GPIO26.ENABLE ( -- ) RTC_GPIO7.ENABLE ;
: GPIO26.OUTPUT_ENABLE ( -- ) RTC_GPIO7.OUTPUT_ENABLE ;
: GPIO26.SET_HIGH ( -- ) RTC_GPIO7.SET_HIGH ;
: GPIO26.SET_LOW ( -- ) RTC_GPIO7.SET_LOW ;
: GPIO26.SET ( n -- ) RTC_GPIO7.SET ;

: GPIO33.ENABLE ( -- ) RTC_GPIO8.ENABLE ;
: GPIO33.OUTPUT_ENABLE ( -- ) RTC_GPIO8.OUTPUT_ENABLE ;
: GPIO33.SET_HIGH ( -- ) RTC_GPIO8.SET_HIGH ;
: GPIO33.SET_LOW ( -- ) RTC_GPIO8.SET_LOW ;
: GPIO33.SET ( n -- ) RTC_GPIO8.SET ;

: GPIO32.ENABLE ( -- ) RTC_GPIO9.ENABLE ;
: GPIO32.OUTPUT_ENABLE ( -- ) RTC_GPIO9.OUTPUT_ENABLE ;
: GPIO32.SET_HIGH ( -- ) RTC_GPIO9.SET_HIGH ;
: GPIO32.SET_LOW ( -- ) RTC_GPIO9.SET_LOW ;
: GPIO32.SET ( n -- ) RTC_GPIO9.SET ;

: GPIO4.ENABLE ( -- ) RTC_GPIO10.ENABLE ;
: GPIO4.OUTPUT_ENABLE ( -- ) RTC_GPIO10.OUTPUT_ENABLE ;
: GPIO4.SET_HIGH ( -- ) RTC_GPIO10.SET_HIGH ;
: GPIO4.SET_LOW ( -- ) RTC_GPIO10.SET_LOW ;
: GPIO4.SET ( n -- ) RTC_GPIO10.SET ;

: GPIO0.ENABLE ( -- ) RTC_GPIO11.ENABLE ;
: GPIO0.OUTPUT_ENABLE ( -- ) RTC_GPIO11.OUTPUT_ENABLE ;
: GPIO0.SET_HIGH ( -- ) RTC_GPIO11.SET_HIGH ;
: GPIO0.SET_LOW ( -- ) RTC_GPIO11.SET_LOW ;
: GPIO0.SET ( n -- ) RTC_GPIO11.SET ;

: GPIO2.ENABLE ( -- ) RTC_GPIO12.ENABLE ;
: GPIO2.OUTPUT_ENABLE ( -- ) RTC_GPIO12.OUTPUT_ENABLE ;
: GPIO2.SET_HIGH ( -- ) RTC_GPIO12.SET_HIGH ;
: GPIO2.SET_LOW ( -- ) RTC_GPIO12.SET_LOW ;
: GPIO2.SET ( n -- ) RTC_GPIO12.SET ;

: GPIO15.ENABLE ( -- ) RTC_GPIO13.ENABLE ;
: GPIO15.OUTPUT_ENABLE ( -- ) RTC_GPIO13.OUTPUT_ENABLE ;
: GPIO15.SET_HIGH ( -- ) RTC_GPIO13.SET_HIGH ;
: GPIO15.SET_LOW ( -- ) RTC_GPIO13.SET_LOW ;
: GPIO15.SET ( n -- ) RTC_GPIO13.SET ;

: GPIO13.ENABLE ( -- ) RTC_GPIO14.ENABLE ;
: GPIO13.OUTPUT_ENABLE ( -- ) RTC_GPIO14.OUTPUT_ENABLE ;
: GPIO13.SET_HIGH ( -- ) RTC_GPIO14.SET_HIGH ;
: GPIO13.SET_LOW ( -- ) RTC_GPIO14.SET_LOW ;
: GPIO13.SET ( n -- ) RTC_GPIO14.SET ;

: GPIO12.ENABLE ( -- ) RTC_GPIO15.ENABLE ;
: GPIO12.OUTPUT_ENABLE ( -- ) RTC_GPIO15.OUTPUT_ENABLE ;
: GPIO12.SET_HIGH ( -- ) RTC_GPIO15.SET_HIGH ;
: GPIO12.SET_LOW ( -- ) RTC_GPIO15.SET_LOW ;
: GPIO12.SET ( n -- ) RTC_GPIO15.SET ;

: GPIO14.ENABLE ( -- ) RTC_GPIO16.ENABLE ;
: GPIO14.OUTPUT_ENABLE ( -- ) RTC_GPIO16.OUTPUT_ENABLE ;
: GPIO14.SET_HIGH ( -- ) RTC_GPIO16.SET_HIGH ;
: GPIO14.SET_LOW ( -- ) RTC_GPIO16.SET_LOW ;
: GPIO14.SET ( n -- ) RTC_GPIO16.SET ;

: GPIO27.ENABLE ( -- ) RTC_GPIO17.ENABLE ;
: GPIO27.OUTPUT_ENABLE ( -- ) RTC_GPIO17.OUTPUT_ENABLE ;
: GPIO27.SET_HIGH ( -- ) RTC_GPIO17.SET_HIGH ;
: GPIO27.SET_LOW ( -- ) RTC_GPIO17.SET_LOW ;
: GPIO27.SET ( n -- ) RTC_GPIO17.SET ;
