\ Copyright 2024-2025 Blake Felt blake.w.felt@gmail.com
\ This Source Code Form is subject to the terms of the Mozilla Public
\ License, v. 2.0. If a copy of the MPL was not distributed with this
\ file, You can obtain one at https://mozilla.org/MPL/2.0/.

\ words to enable RTC_GPIO

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE1_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE1_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO0.ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE2_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE2_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO1.ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE3_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE3_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO2.ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE4_MUX_SEL_S 1 1
RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE4_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO3.ENABLE

RTCIO_ADC_PAD_REG RTCIO_ADC_ADC1_MUX_SEL_S 1 1
RTCIO_ADC_PAD_REG RTCIO_ADC_ADC1_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO4.ENABLE

RTCIO_ADC_PAD_REG RTCIO_ADC_ADC2_MUX_SEL_S 1 1
RTCIO_ADC_PAD_REG RTCIO_ADC_ADC2_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO5.ENABLE

RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_MUX_SEL_S 1 1
RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO6.ENABLE

RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_MUX_SEL_S 1 1
RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO7.ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_MUX_SEL_S 1 1
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO8.ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_MUX_SEL_S 1 1
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO9.ENABLE

RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO10.ENABLE

RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO11.ENABLE

RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO12.ENABLE

RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO13.ENABLE

RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO14.ENABLE

RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO15.ENABLE

RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO16.ENABLE

RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_MUX_SEL_S 1 1
RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_FUN_SEL_S 2 0
2WRITE_RTC_REG RTC_GPIO17.ENABLE

\ words to enable output on RTC_GPIO

: --CREATE-OUTPUTENABLE ( n -- )
    RTCIO_RTC_GPIO_ENABLE_W1TS_REG
    SWAP RTCIO_RTC_GPIO_ENABLE_W1TS_S +
    1 1
    WRITE_RTC_REG
;

6  --CREATE-OUTPUTENABLE RTC_GPIO6.OUTPUT_ENABLE
7  --CREATE-OUTPUTENABLE RTC_GPIO7.OUTPUT_ENABLE
8  --CREATE-OUTPUTENABLE RTC_GPIO8.OUTPUT_ENABLE
9  --CREATE-OUTPUTENABLE RTC_GPIO9.OUTPUT_ENABLE
10 --CREATE-OUTPUTENABLE RTC_GPIO10.OUTPUT_ENABLE
11 --CREATE-OUTPUTENABLE RTC_GPIO11.OUTPUT_ENABLE
12 --CREATE-OUTPUTENABLE RTC_GPIO12.OUTPUT_ENABLE
13 --CREATE-OUTPUTENABLE RTC_GPIO13.OUTPUT_ENABLE
14 --CREATE-OUTPUTENABLE RTC_GPIO14.OUTPUT_ENABLE
15 --CREATE-OUTPUTENABLE RTC_GPIO15.OUTPUT_ENABLE
16 --CREATE-OUTPUTENABLE RTC_GPIO16.OUTPUT_ENABLE
17 --CREATE-OUTPUTENABLE RTC_GPIO17.OUTPUT_ENABLE

\ words to disable output on RTC_GPIO

: --CREATE-OUTPUTDISABLE ( n -- )
    RTCIO_RTC_GPIO_ENABLE_W1TC_REG
    SWAP RTCIO_RTC_GPIO_ENABLE_W1TC_S +
    1 1
    WRITE_RTC_REG
;

6  --CREATE-OUTPUTDISABLE RTC_GPIO6.OUTPUT_DISABLE
7  --CREATE-OUTPUTDISABLE RTC_GPIO7.OUTPUT_DISABLE
8  --CREATE-OUTPUTDISABLE RTC_GPIO8.OUTPUT_DISABLE
9  --CREATE-OUTPUTDISABLE RTC_GPIO9.OUTPUT_DISABLE
10 --CREATE-OUTPUTDISABLE RTC_GPIO10.OUTPUT_DISABLE
11 --CREATE-OUTPUTDISABLE RTC_GPIO11.OUTPUT_DISABLE
12 --CREATE-OUTPUTDISABLE RTC_GPIO12.OUTPUT_DISABLE
13 --CREATE-OUTPUTDISABLE RTC_GPIO13.OUTPUT_DISABLE
14 --CREATE-OUTPUTDISABLE RTC_GPIO14.OUTPUT_DISABLE
15 --CREATE-OUTPUTDISABLE RTC_GPIO15.OUTPUT_DISABLE
16 --CREATE-OUTPUTDISABLE RTC_GPIO16.OUTPUT_DISABLE
17 --CREATE-OUTPUTDISABLE RTC_GPIO17.OUTPUT_DISABLE

\ words to enable input on RTC_GPIO

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE1_MUX_SEL_S 1 1
WRITE_RTC_REG RTC_GPIO0.INPUT_ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE2_MUX_SEL_S 1 1
WRITE_RTC_REG RTC_GPIO1.INPUT_ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE3_MUX_SEL_S 1 1
WRITE_RTC_REG RTC_GPIO2.INPUT_ENABLE

RTCIO_SENSOR_PADS_REG RTCIO_SENSOR_SENSE4_MUX_SEL_S 1 1
WRITE_RTC_REG RTC_GPIO3.INPUT_ENABLE

RTCIO_ADC_PAD_REG RTCIO_ADC_ADC1_FUN_SEL_S 1 1
WRITE_RTC_REG RTC_GPIO4.INPUT_ENABLE

RTCIO_ADC_PAD_REG RTCIO_ADC_ADC2_FUN_SEL_S 1 1
WRITE_RTC_REG RTC_GPIO5.INPUT_ENABLE

RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO6.INPUT_ENABLE

RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO7.INPUT_ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO8.INPUT_ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO9.INPUT_ENABLE

RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO10.INPUT_ENABLE

RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO11.INPUT_ENABLE

RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO12.INPUT_ENABLE

RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO13.INPUT_ENABLE

RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO14.INPUT_ENABLE

RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO15.INPUT_ENABLE

RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO16.INPUT_ENABLE

RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_FUN_IE_S 1 1
WRITE_RTC_REG RTC_GPIO17.INPUT_ENABLE

\ words to set RTC_GPIO high

: --CREATE-SETHIGH ( n -- )
    RTCIO_RTC_GPIO_OUT_W1TS_REG
    SWAP RTCIO_RTC_GPIO_OUT_DATA_W1TS_S +
    1 1
    WRITE_RTC_REG
;

6  --CREATE-SETHIGH RTC_GPIO6.SET_HIGH
7  --CREATE-SETHIGH RTC_GPIO7.SET_HIGH
8  --CREATE-SETHIGH RTC_GPIO8.SET_HIGH
9  --CREATE-SETHIGH RTC_GPIO9.SET_HIGH
10 --CREATE-SETHIGH RTC_GPIO10.SET_HIGH
11 --CREATE-SETHIGH RTC_GPIO11.SET_HIGH
12 --CREATE-SETHIGH RTC_GPIO12.SET_HIGH
13 --CREATE-SETHIGH RTC_GPIO13.SET_HIGH
14 --CREATE-SETHIGH RTC_GPIO14.SET_HIGH
15 --CREATE-SETHIGH RTC_GPIO15.SET_HIGH
16 --CREATE-SETHIGH RTC_GPIO16.SET_HIGH
17 --CREATE-SETHIGH RTC_GPIO17.SET_HIGH

\ words to set RTC_GPIO low

: --CREATE-SETLOW ( n -- )
    RTCIO_RTC_GPIO_OUT_W1TC_REG
    SWAP RTCIO_RTC_GPIO_OUT_DATA_W1TC_S +
    1 1
    WRITE_RTC_REG
;

6  --CREATE-SETLOW RTC_GPIO6.SET_LOW
7  --CREATE-SETLOW RTC_GPIO7.SET_LOW
8  --CREATE-SETLOW RTC_GPIO8.SET_LOW
9  --CREATE-SETLOW RTC_GPIO9.SET_LOW
10 --CREATE-SETLOW RTC_GPIO10.SET_LOW
11 --CREATE-SETLOW RTC_GPIO11.SET_LOW
12 --CREATE-SETLOW RTC_GPIO12.SET_LOW
13 --CREATE-SETLOW RTC_GPIO13.SET_LOW
14 --CREATE-SETLOW RTC_GPIO14.SET_LOW
15 --CREATE-SETLOW RTC_GPIO15.SET_LOW
16 --CREATE-SETLOW RTC_GPIO16.SET_LOW
17 --CREATE-SETLOW RTC_GPIO17.SET_LOW


\ words to get RTC_GPIO levels
\
\ these are done separately for speed
\ and consistent read times

: --CREATE-GET ( n -- )
    RTCIO_RTC_GPIO_IN_REG
    SWAP RTCIO_RTC_GPIO_IN_NEXT_S +
    1
    READ_RTC_REG
;

0  --CREATE-GET RTC_GPIO0.GET
1  --CREATE-GET RTC_GPIO1.GET
2  --CREATE-GET RTC_GPIO2.GET
3  --CREATE-GET RTC_GPIO3.GET
4  --CREATE-GET RTC_GPIO4.GET
5  --CREATE-GET RTC_GPIO5.GET
6  --CREATE-GET RTC_GPIO6.GET
7  --CREATE-GET RTC_GPIO7.GET
8  --CREATE-GET RTC_GPIO8.GET
9  --CREATE-GET RTC_GPIO9.GET
10 --CREATE-GET RTC_GPIO10.GET
11 --CREATE-GET RTC_GPIO11.GET
12 --CREATE-GET RTC_GPIO12.GET
13 --CREATE-GET RTC_GPIO13.GET
14 --CREATE-GET RTC_GPIO14.GET
15 --CREATE-GET RTC_GPIO15.GET
16 --CREATE-GET RTC_GPIO16.GET
17 --CREATE-GET RTC_GPIO17.GET

\ words to enable and disable RTC_GPIO pullups

\ 6
RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO6.PULLUP_ENABLE

RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO6.PULLUP_DISABLE

\ 7
RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO7.PULLUP_ENABLE

RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO7.PULLUP_DISABLE

\ 8
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO8.PULLUP_ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO8.PULLUP_DISABLE

\ 9
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO9.PULLUP_ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO9.PULLUP_DISABLE

\ 10
RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO10.PULLUP_ENABLE

RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO10.PULLUP_DISABLE

\ 11
RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO11.PULLUP_ENABLE

RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO11.PULLUP_DISABLE

\ 12
RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO12.PULLUP_ENABLE

RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO12.PULLUP_DISABLE

\ 13
RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO13.PULLUP_ENABLE

RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO13.PULLUP_DISABLE

\ 14
RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO14.PULLUP_ENABLE

RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO14.PULLUP_DISABLE

\ 15
RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO15.PULLUP_ENABLE

RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO15.PULLUP_DISABLE

\ 16
RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO16.PULLUP_ENABLE

RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO16.PULLUP_DISABLE

\ 17
RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_RUE_S 1 1
WRITE_RTC_REG RTC_GPIO17.PULLUP_ENABLE

RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_RUE_S 1 0
WRITE_RTC_REG RTC_GPIO17.PULLUP_DISABLE


\ words to enable and disable RTC_GPIO pulldowns

\ 6
RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO6.PULLDOWN_ENABLE

RTCIO_PAD_DAC1_REG RTCIO_PAD_PDACn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO6.PULLDOWN_DISABLE

\ 7
RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO7.PULLDOWN_ENABLE

RTCIO_PAD_DAC2_REG RTCIO_PAD_PDACn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO7.PULLDOWN_DISABLE

\ 8
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO8.PULLDOWN_ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32N_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO8.PULLDOWN_DISABLE

\ 9
RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO9.PULLDOWN_ENABLE

RTCIO_XTAL_32K_PAD_REG RTCIO_XTAL_X32P_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO9.PULLDOWN_DISABLE

\ 10
RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO10.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD0_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO10.PULLDOWN_DISABLE

\ 11
RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO11.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD1_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO11.PULLDOWN_DISABLE

\ 12
RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO12.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD2_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO12.PULLDOWN_DISABLE

\ 13
RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO13.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD3_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO13.PULLDOWN_DISABLE

\ 14
RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO14.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD4_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO14.PULLDOWN_DISABLE

\ 15
RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO15.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD5_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO15.PULLDOWN_DISABLE

\ 16
RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO16.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD6_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO16.PULLDOWN_DISABLE

\ 17
RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_RDE_S 1 1
WRITE_RTC_REG RTC_GPIO17.PULLDOWN_ENABLE

RTCIO_TOUCH_PAD7_REG RTCIO_TOUCH_PADn_RDE_S 1 0
WRITE_RTC_REG RTC_GPIO17.PULLDOWN_DISABLE

\ helper words to set RTC_GPIO levels

: RTC_GPIO6.SET  ( n -- ) IF RTC_GPIO6.SET_HIGH  EXIT THEN RTC_GPIO6.SET_LOW  ;
: RTC_GPIO7.SET  ( n -- ) IF RTC_GPIO7.SET_HIGH  EXIT THEN RTC_GPIO7.SET_LOW  ;
: RTC_GPIO8.SET  ( n -- ) IF RTC_GPIO8.SET_HIGH  EXIT THEN RTC_GPIO8.SET_LOW  ;
: RTC_GPIO9.SET  ( n -- ) IF RTC_GPIO9.SET_HIGH  EXIT THEN RTC_GPIO9.SET_LOW  ;
: RTC_GPIO10.SET ( n -- ) IF RTC_GPIO10.SET_HIGH EXIT THEN RTC_GPIO10.SET_LOW ;
: RTC_GPIO11.SET ( n -- ) IF RTC_GPIO11.SET_HIGH EXIT THEN RTC_GPIO11.SET_LOW ;
: RTC_GPIO12.SET ( n -- ) IF RTC_GPIO12.SET_HIGH EXIT THEN RTC_GPIO12.SET_LOW ;
: RTC_GPIO13.SET ( n -- ) IF RTC_GPIO13.SET_HIGH EXIT THEN RTC_GPIO13.SET_LOW ;
: RTC_GPIO14.SET ( n -- ) IF RTC_GPIO14.SET_HIGH EXIT THEN RTC_GPIO14.SET_LOW ;
: RTC_GPIO15.SET ( n -- ) IF RTC_GPIO15.SET_HIGH EXIT THEN RTC_GPIO15.SET_LOW ;
: RTC_GPIO16.SET ( n -- ) IF RTC_GPIO16.SET_HIGH EXIT THEN RTC_GPIO16.SET_LOW ;
: RTC_GPIO17.SET ( n -- ) IF RTC_GPIO17.SET_HIGH EXIT THEN RTC_GPIO17.SET_LOW ;

\ GPIO equivalents

: GPIO36.ENABLE ( -- ) RTC_GPIO0.ENABLE ;
: GPIO36.INPUT_ENABLE ( -- ) RTC_GPIO0.INPUT_ENABLE ;
: GPIO36.GET ( -- n ) RTC_GPIO0.GET ;

: GPIO37.ENABLE ( -- ) RTC_GPIO1.ENABLE ;
: GPIO37.INPUT_ENABLE ( -- ) RTC_GPIO1.INPUT_ENABLE ;
: GPIO37.GET ( -- n ) RTC_GPIO1.GET ;

: GPIO38.ENABLE ( -- ) RTC_GPIO2.ENABLE ;
: GPIO38.INPUT_ENABLE ( -- ) RTC_GPIO2.INPUT_ENABLE ;
: GPIO38.GET ( -- n ) RTC_GPIO2.GET ;

: GPIO39.ENABLE ( -- ) RTC_GPIO3.ENABLE ;
: GPIO39.INPUT_ENABLE ( -- ) RTC_GPIO3.INPUT_ENABLE ;
: GPIO39.GET ( -- n ) RTC_GPIO3.GET ;

: GPIO34.ENABLE ( -- ) RTC_GPIO4.ENABLE ;
: GPIO34.INPUT_ENABLE ( -- ) RTC_GPIO4.INPUT_ENABLE ;
: GPIO34.GET ( -- n ) RTC_GPIO4.GET ;

: GPIO35.ENABLE ( -- ) RTC_GPIO5.ENABLE ;
: GPIO35.INPUT_ENABLE ( -- ) RTC_GPIO5.INPUT_ENABLE ;
: GPIO35.GET ( -- n ) RTC_GPIO5.GET ;

: GPIO25.ENABLE ( -- ) RTC_GPIO6.ENABLE ;
: GPIO25.OUTPUT_ENABLE ( -- ) RTC_GPIO6.OUTPUT_ENABLE ;
: GPIO25.OUTPUT_DISABLE ( -- ) RTC_GPIO6.OUTPUT_DISABLE ;
: GPIO25.INPUT_ENABLE ( -- ) RTC_GPIO6.INPUT_ENABLE ;
: GPIO25.SET_HIGH ( -- ) RTC_GPIO6.SET_HIGH ;
: GPIO25.SET_LOW ( -- ) RTC_GPIO6.SET_LOW ;
: GPIO25.SET ( n -- ) RTC_GPIO6.SET ;
: GPIO25.GET ( -- n ) RTC_GPIO6.GET ;
: GPIO25.PULLUP_ENABLE ( -- ) RTC_GPIO6.PULLUP_ENABLE ;
: GPIO25.PULLUP_DISABLE ( -- ) RTC_GPIO6.PULLUP_DISABLE ;
: GPIO25.PULLDOWN_ENABLE ( -- ) RTC_GPIO6.PULLDOWN_ENABLE ;
: GPIO25.PULLDOWN_DISABLE ( -- ) RTC_GPIO6.PULLDOWN_DISABLE ;

: GPIO26.ENABLE ( -- ) RTC_GPIO7.ENABLE ;
: GPIO26.OUTPUT_ENABLE ( -- ) RTC_GPIO7.OUTPUT_ENABLE ;
: GPIO26.OUTPUT_DISABLE ( -- ) RTC_GPIO7.OUTPUT_DISABLE ;
: GPIO26.INPUT_ENABLE ( -- ) RTC_GPIO7.INPUT_ENABLE ;
: GPIO26.SET_HIGH ( -- ) RTC_GPIO7.SET_HIGH ;
: GPIO26.SET_LOW ( -- ) RTC_GPIO7.SET_LOW ;
: GPIO26.SET ( n -- ) RTC_GPIO7.SET ;
: GPIO26.GET ( -- n ) RTC_GPIO7.GET ;
: GPIO26.PULLUP_ENABLE ( -- ) RTC_GPIO7.PULLUP_ENABLE ;
: GPIO26.PULLUP_DISABLE ( -- ) RTC_GPIO7.PULLUP_DISABLE ;
: GPIO26.PULLDOWN_ENABLE ( -- ) RTC_GPIO7.PULLDOWN_ENABLE ;
: GPIO26.PULLDOWN_DISABLE ( -- ) RTC_GPIO7.PULLDOWN_DISABLE ;

: GPIO33.ENABLE ( -- ) RTC_GPIO8.ENABLE ;
: GPIO33.OUTPUT_ENABLE ( -- ) RTC_GPIO8.OUTPUT_ENABLE ;
: GPIO33.OUTPUT_DISABLE ( -- ) RTC_GPIO8.OUTPUT_DISABLE ;
: GPIO33.INPUT_ENABLE ( -- ) RTC_GPIO8.INPUT_ENABLE ;
: GPIO33.SET_HIGH ( -- ) RTC_GPIO8.SET_HIGH ;
: GPIO33.SET_LOW ( -- ) RTC_GPIO8.SET_LOW ;
: GPIO33.SET ( n -- ) RTC_GPIO8.SET ;
: GPIO33.GET ( -- n ) RTC_GPIO8.GET ;
: GPIO33.PULLUP_ENABLE ( -- ) RTC_GPIO8.PULLUP_ENABLE ;
: GPIO33.PULLUP_DISABLE ( -- ) RTC_GPIO8.PULLUP_DISABLE ;
: GPIO33.PULLDOWN_ENABLE ( -- ) RTC_GPIO8.PULLDOWN_ENABLE ;
: GPIO33.PULLDOWN_DISABLE ( -- ) RTC_GPIO8.PULLDOWN_DISABLE ;

: GPIO32.ENABLE ( -- ) RTC_GPIO9.ENABLE ;
: GPIO32.OUTPUT_ENABLE ( -- ) RTC_GPIO9.OUTPUT_ENABLE ;
: GPIO32.OUTPUT_DISABLE ( -- ) RTC_GPIO9.OUTPUT_DISABLE ;
: GPIO32.INPUT_ENABLE ( -- ) RTC_GPIO9.INPUT_ENABLE ;
: GPIO32.SET_HIGH ( -- ) RTC_GPIO9.SET_HIGH ;
: GPIO32.SET_LOW ( -- ) RTC_GPIO9.SET_LOW ;
: GPIO32.SET ( n -- ) RTC_GPIO9.SET ;
: GPIO32.GET ( -- n ) RTC_GPIO9.GET ;
: GPIO32.PULLUP_ENABLE ( -- ) RTC_GPIO9.PULLUP_ENABLE ;
: GPIO32.PULLUP_DISABLE ( -- ) RTC_GPIO9.PULLUP_DISABLE ;
: GPIO32.PULLDOWN_ENABLE ( -- ) RTC_GPIO9.PULLDOWN_ENABLE ;
: GPIO32.PULLDOWN_DISABLE ( -- ) RTC_GPIO9.PULLDOWN_DISABLE ;

: GPIO4.ENABLE ( -- ) RTC_GPIO10.ENABLE ;
: GPIO4.OUTPUT_ENABLE ( -- ) RTC_GPIO10.OUTPUT_ENABLE ;
: GPIO4.OUTPUT_DISABLE ( -- ) RTC_GPIO10.OUTPUT_DISABLE ;
: GPIO4.INPUT_ENABLE ( -- ) RTC_GPIO10.INPUT_ENABLE ;
: GPIO4.SET_HIGH ( -- ) RTC_GPIO10.SET_HIGH ;
: GPIO4.SET_LOW ( -- ) RTC_GPIO10.SET_LOW ;
: GPIO4.SET ( n -- ) RTC_GPIO10.SET ;
: GPIO4.GET ( -- n ) RTC_GPIO10.GET ;
: GPIO4.PULLUP_ENABLE ( -- ) RTC_GPIO10.PULLUP_ENABLE ;
: GPIO4.PULLUP_DISABLE ( -- ) RTC_GPIO10.PULLUP_DISABLE ;
: GPIO4.PULLDOWN_ENABLE ( -- ) RTC_GPIO10.PULLDOWN_ENABLE ;
: GPIO4.PULLDOWN_DISABLE ( -- ) RTC_GPIO10.PULLDOWN_DISABLE ;

: GPIO0.ENABLE ( -- ) RTC_GPIO11.ENABLE ;
: GPIO0.OUTPUT_ENABLE ( -- ) RTC_GPIO11.OUTPUT_ENABLE ;
: GPIO0.OUTPUT_DISABLE ( -- ) RTC_GPIO11.OUTPUT_DISABLE ;
: GPIO0.INPUT_ENABLE ( -- ) RTC_GPIO11.INPUT_ENABLE ;
: GPIO0.SET_HIGH ( -- ) RTC_GPIO11.SET_HIGH ;
: GPIO0.SET_LOW ( -- ) RTC_GPIO11.SET_LOW ;
: GPIO0.SET ( n -- ) RTC_GPIO11.SET ;
: GPIO0.GET ( -- n ) RTC_GPIO11.GET ;
: GPIO0.PULLUP_ENABLE ( -- ) RTC_GPIO11.PULLUP_ENABLE ;
: GPIO0.PULLUP_DISABLE ( -- ) RTC_GPIO11.PULLUP_DISABLE ;
: GPIO0.PULLDOWN_ENABLE ( -- ) RTC_GPIO11.PULLDOWN_ENABLE ;
: GPIO0.PULLDOWN_DISABLE ( -- ) RTC_GPIO11.PULLDOWN_DISABLE ;

: GPIO2.ENABLE ( -- ) RTC_GPIO12.ENABLE ;
: GPIO2.OUTPUT_ENABLE ( -- ) RTC_GPIO12.OUTPUT_ENABLE ;
: GPIO2.OUTPUT_DISABLE ( -- ) RTC_GPIO12.OUTPUT_DISABLE ;
: GPIO2.INPUT_ENABLE ( -- ) RTC_GPIO12.INPUT_ENABLE ;
: GPIO2.SET_HIGH ( -- ) RTC_GPIO12.SET_HIGH ;
: GPIO2.SET_LOW ( -- ) RTC_GPIO12.SET_LOW ;
: GPIO2.SET ( n -- ) RTC_GPIO12.SET ;
: GPIO2.GET ( -- n ) RTC_GPIO12.GET ;
: GPIO2.PULLUP_ENABLE ( -- ) RTC_GPIO12.PULLUP_ENABLE ;
: GPIO2.PULLUP_DISABLE ( -- ) RTC_GPIO12.PULLUP_DISABLE ;
: GPIO2.PULLDOWN_ENABLE ( -- ) RTC_GPIO12.PULLDOWN_ENABLE ;
: GPIO2.PULLDOWN_DISABLE ( -- ) RTC_GPIO12.PULLDOWN_DISABLE ;

: GPIO15.ENABLE ( -- ) RTC_GPIO13.ENABLE ;
: GPIO15.OUTPUT_ENABLE ( -- ) RTC_GPIO13.OUTPUT_ENABLE ;
: GPIO15.OUTPUT_DISABLE ( -- ) RTC_GPIO13.OUTPUT_DISABLE ;
: GPIO15.INPUT_ENABLE ( -- ) RTC_GPIO13.INPUT_ENABLE ;
: GPIO15.SET_HIGH ( -- ) RTC_GPIO13.SET_HIGH ;
: GPIO15.SET_LOW ( -- ) RTC_GPIO13.SET_LOW ;
: GPIO15.SET ( n -- ) RTC_GPIO13.SET ;
: GPIO15.GET ( -- n ) RTC_GPIO13.GET ;
: GPIO15.PULLUP_ENABLE ( -- ) RTC_GPIO13.PULLUP_ENABLE ;
: GPIO15.PULLUP_DISABLE ( -- ) RTC_GPIO13.PULLUP_DISABLE ;
: GPIO15.PULLDOWN_ENABLE ( -- ) RTC_GPIO13.PULLDOWN_ENABLE ;
: GPIO15.PULLDOWN_DISABLE ( -- ) RTC_GPIO13.PULLDOWN_DISABLE ;

: GPIO13.ENABLE ( -- ) RTC_GPIO14.ENABLE ;
: GPIO13.OUTPUT_ENABLE ( -- ) RTC_GPIO14.OUTPUT_ENABLE ;
: GPIO13.OUTPUT_DISABLE ( -- ) RTC_GPIO14.OUTPUT_DISABLE ;
: GPIO13.INPUT_ENABLE ( -- ) RTC_GPIO14.INPUT_ENABLE ;
: GPIO13.SET_HIGH ( -- ) RTC_GPIO14.SET_HIGH ;
: GPIO13.SET_LOW ( -- ) RTC_GPIO14.SET_LOW ;
: GPIO13.SET ( n -- ) RTC_GPIO14.SET ;
: GPIO13.GET ( -- n ) RTC_GPIO14.GET ;
: GPIO13.PULLUP_ENABLE ( -- ) RTC_GPIO14.PULLUP_ENABLE ;
: GPIO13.PULLUP_DISABLE ( -- ) RTC_GPIO14.PULLUP_DISABLE ;
: GPIO13.PULLDOWN_ENABLE ( -- ) RTC_GPIO14.PULLDOWN_ENABLE ;
: GPIO13.PULLDOWN_DISABLE ( -- ) RTC_GPIO14.PULLDOWN_DISABLE ;

: GPIO12.ENABLE ( -- ) RTC_GPIO15.ENABLE ;
: GPIO12.OUTPUT_ENABLE ( -- ) RTC_GPIO15.OUTPUT_ENABLE ;
: GPIO12.OUTPUT_DISABLE ( -- ) RTC_GPIO15.OUTPUT_DISABLE ;
: GPIO12.INPUT_ENABLE ( -- ) RTC_GPIO15.INPUT_ENABLE ;
: GPIO12.SET_HIGH ( -- ) RTC_GPIO15.SET_HIGH ;
: GPIO12.SET_LOW ( -- ) RTC_GPIO15.SET_LOW ;
: GPIO12.SET ( n -- ) RTC_GPIO15.SET ;
: GPIO12.GET ( -- n ) RTC_GPIO15.GET ;
: GPIO12.PULLUP_ENABLE ( -- ) RTC_GPIO15.PULLUP_ENABLE ;
: GPIO12.PULLUP_DISABLE ( -- ) RTC_GPIO15.PULLUP_DISABLE ;
: GPIO12.PULLDOWN_ENABLE ( -- ) RTC_GPIO15.PULLDOWN_ENABLE ;
: GPIO12.PULLDOWN_DISABLE ( -- ) RTC_GPIO15.PULLDOWN_DISABLE ;

: GPIO14.ENABLE ( -- ) RTC_GPIO16.ENABLE ;
: GPIO14.OUTPUT_ENABLE ( -- ) RTC_GPIO16.OUTPUT_ENABLE ;
: GPIO14.OUTPUT_DISABLE ( -- ) RTC_GPIO16.OUTPUT_DISABLE ;
: GPIO14.INPUT_ENABLE ( -- ) RTC_GPIO16.INPUT_ENABLE ;
: GPIO14.SET_HIGH ( -- ) RTC_GPIO16.SET_HIGH ;
: GPIO14.SET_LOW ( -- ) RTC_GPIO16.SET_LOW ;
: GPIO14.SET ( n -- ) RTC_GPIO16.SET ;
: GPIO14.GET ( -- n ) RTC_GPIO16.GET ;
: GPIO14.PULLUP_ENABLE ( -- ) RTC_GPIO16.PULLUP_ENABLE ;
: GPIO14.PULLUP_DISABLE ( -- ) RTC_GPIO16.PULLUP_DISABLE ;
: GPIO14.PULLDOWN_ENABLE ( -- ) RTC_GPIO16.PULLDOWN_ENABLE ;
: GPIO14.PULLDOWN_DISABLE ( -- ) RTC_GPIO16.PULLDOWN_DISABLE ;

: GPIO27.ENABLE ( -- ) RTC_GPIO17.ENABLE ;
: GPIO27.OUTPUT_ENABLE ( -- ) RTC_GPIO17.OUTPUT_ENABLE ;
: GPIO27.OUTPUT_DISABLE ( -- ) RTC_GPIO17.OUTPUT_DISABLE ;
: GPIO27.INPUT_ENABLE ( -- ) RTC_GPIO17.INPUT_ENABLE ;
: GPIO27.SET_HIGH ( -- ) RTC_GPIO17.SET_HIGH ;
: GPIO27.SET_LOW ( -- ) RTC_GPIO17.SET_LOW ;
: GPIO27.SET ( n -- ) RTC_GPIO17.SET ;
: GPIO27.GET ( -- n ) RTC_GPIO17.GET ;
: GPIO27.PULLUP_ENABLE ( -- ) RTC_GPIO17.PULLUP_ENABLE ;
: GPIO27.PULLUP_DISABLE ( -- ) RTC_GPIO17.PULLUP_DISABLE ;
: GPIO27.PULLDOWN_ENABLE ( -- ) RTC_GPIO17.PULLDOWN_ENABLE ;
: GPIO27.PULLDOWN_DISABLE ( -- ) RTC_GPIO17.PULLDOWN_DISABLE ;

: GPIO_NUMBER_TO_RTC ( gpio_num -- rtc_gpio_num )
    CASE
        36 OF 0  ENDOF
        37 OF 1  ENDOF
        38 OF 2  ENDOF
        39 OF 3  ENDOF
        34 OF 4  ENDOF
        35 OF 5  ENDOF
        25 OF 6  ENDOF
        26 OF 7  ENDOF
        33 OF 8  ENDOF
        32 OF 9  ENDOF
        4  OF 10 ENDOF
        0  OF 11 ENDOF
        2  OF 12 ENDOF
        15 OF 13 ENDOF
        13 OF 14 ENDOF
        12 OF 15 ENDOF
        14 OF 16 ENDOF
        27 OF 17 ENDOF
        ." ERROR: Invalid gpio number " DUP . CR
    ENDCASE
;
